### ISSUE TITLE
`carthage build` failing on `master` for Xcode 14.0.1

### ISSUE THREAD

**Issue by gemmakbarlow** [AppsFlyerSDK/segment-appsflyer-ios#90]
I'm trying to use `carthage` to generate dependencies needed to build [segment-appsflyer-ios.xcodeproj](https://github.com/AppsFlyerSDK/segment-appsflyer-ios/tree/master/segment-appsflyer-ios.xcodeproj) and am running into the following issue - 

![image](https://user-images.githubusercontent.com/337963/203393052-326cccea-0f6f-4470-a5ba-211ddd4c5d2c.png)

Building via Swift Package Manager is working nicely ✅ 

Can you confirm the build script / commands that are typically used for this project ? If so, I'm happy to put up a PR for adding a **Contributing** section to the wiki.

**Comment by morisgateno-appsflyer** [comment]
Hi @gemmakbarlow, Sorry for the delay.
We understand there is a problem with Carthage. The issue is due to a problem in building a scheme on Segment side.
Here is the problem : [Segment issue](https://github.com/segmentio/analytics-ios/pull/1038).
We are currently not compatible with Carthage.
If you have any further questions please contact [support@appsflyer.com](mailto:support@appsflyer.com).
Moris(Appsflyer).

**Comment by gemmakbarlow** [comment]
Ah OK - thanks Moris. Appreciate the response.
